name 'Install_SQL_Server_2014_SP1'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Install_SQL_Server_2014_SP1'
long_description 'Installs/Configures Install_SQL_Server_2014_SP1'
version '0.1.0'
