name 'Install_Chef_Client_Win_Service_10_MIC'
maintainer 'Ryan Irujo'
maintainer_email 'ryan.irujo@gmail.com'
license 'GPL v3'
description 'Installs/Configures Install_Chef_Client_Win_Service_10_MIC'
long_description 'Installs and Configures the Chef Client Windows Service to run every 10 minutes.'
version '0.1.0'
